name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  # -------------------------
  # 1. Run Unit Tests
  # -------------------------
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Send Email if Tests Fail
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "❌ CI Test Failure in FlaskApp"
          to: "your-email@example.com"
          from: "CI Bot <your-email@example.com>"
          body: "Tests have failed in the CI pipeline. Please review the logs."

  # -------------------------
  # 2. Build Docker Image (parallel job)
  # -------------------------
  build_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t flaskapp:latest .

  # -------------------------
  # 3. Push to Docker Hub & Private Registry
  # -------------------------
  push_image:
    runs-on: ubuntu-latest
    needs: 
      - tests
      - build_docker
    if: ${{ needs.tests.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Tag and Push to Docker Hub
      - name: Push to Docker Hub
        run: |
          docker tag flaskapp:latest chay2406/flaskapp:latest
          docker push chay2406/flaskapp:latest

      # Login to Second Registry (Private Registry Example)
      - name: Log in to Private Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY_URL }}
          username: ${{ secrets.PRIVATE_REGISTRY_USER }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASS }}

      # Tag & Push to Private Registry
      - name: Push to Private Registry
        run: |
          docker tag flaskapp:latest ${{ secrets.PRIVATE_REGISTRY_URL }}/flaskapp:latest
          docker push ${{ secrets.PRIVATE_REGISTRY_URL }}/flaskapp:latest
